version: '3.3'
services:
  db:
    # Change the img if u need, recomended versions 5.7 or 8.0
    image: mysql:5.7
    container_name: base-de-datos-parcial
    restart: always
    environment:
      MYSQL_DATABASE: 'olympics'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port used for access> : <MySQL Port running inside container>
      - '3310:3306'
    expose:
      # Opens port 3306 on the container
      - '3310'
    volumes:
      # Where our data will be persisted
      - /home/juan-dev/Escritorio/facultad/tercer_año/segundo_cuatri/base_de_datos/proyectos/practico_2/db_data:/mysql/data